name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Access CLIENT_ID
        env:
          APOD_API_KEY: ${{ secrets.CLIENT_ID }}
        run: echo CLIENT_ID=\"$CLIENT_ID\" > ./local.properties

      - name: Access REDIRECT_URI
        env:
          APOD_API_KEY: ${{ secrets.REDIRECT_URI }}
        run: echo REDIRECT_URI=\"$REDIRECT_URI\" > ./local.properties

      - name: Access BASE_URL
        env:
          APOD_API_KEY: ${{ secrets.BASE_URL }}
        run: echo BASE_URL=\"$BASE_URL\" > ./local.properties

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew build