name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    env:
      ENCRYPTED_SERVICES_PATH: ${{ 'app/google-services.json.gpg' }}
      DECRYPTED_SERVICES_PATH: ${{ 'app/google-services.json' }}
      SERVICES_PW: ${{ secrets.GOOGLE_SERVICES_PW }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: decode google-services.json
        run: gpg --pinentry-mode=loopback --passphrase  "$SERVICES_PW" -d -o "$DECRYPTED_SERVICES_PATH" "$ENCRYPTED_SERVICES_PATH"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run test
        run: ./gradlew test