name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt')}}
          restore-keys: |
            ${{runner.os}}-gradle-
            
      - name: Access GOOGLE_SERVICES
        run: echo '${{ secrets.GOOGLE_SERVICES }}' > ./app/google-services.json

      - name: Access CLIENT_ID
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: echo CLIENT_ID=\"$CLIENT_ID\" >> ./local.properties

      - name: Access REDIRECT_URI
        env:
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        run: echo REDIRECT_URI=\"$REDIRECT_URI\" >> ./local.properties

      - name: Access BASE_URL
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: echo BASE_URL=\"$BASE_URL\" >> ./local.properties

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run Lint
        run: ./gradlew lint

      - name: Build with Gradle
        run: ./gradlew build
